language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meshblu-connector' ]; then cd .. && eval "mv $currentfolder generator-meshblu-connector" && cd generator-meshblu-connector; fi

